server:
  port: 19092

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
